### ISSUE TITLE
Not launch on macOS Monterey

### ISSUE THREAD

**Issue by AlexeyPavlyuck** [arpandaze/NoMenuBar#2]
<img width="109" alt="Снимок экрана 2022-09-17 в 00 49 16" src="https://user-images.githubusercontent.com/63820958/190802981-f401d4d2-0d44-49c4-aa9b-1a675dfd1a68.png">

**Comment by AlexeyPavlyuck** [comment]
Please make 64 bit version

**Comment by arpandaze** [comment]
Sorry for late reply.

I am also on Monterey and its working fine for me. Can you please try to compile it from source and test?
